language: go

go:
  - tip
  
install: true

matrix:
  fast_finish: true

notifications:
  email: false

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgdk-pixbuf2.0-dev libgtk2.0-dev libpango1.0-dev
  - go get github.com/guitmz/go-weatherbit
  - go get github.com/mattn/go-gtk

script:
   - go build -i -v .
